#version: '3.8'

services:
  receiver-service:
    build:
      context: .
      dockerfile: ./receiver-service/Dockerfile
    container_name: con-receiver
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - gendata-network
    restart: unless-stopped

  generator-service:
    build:
      context: .
      dockerfile: ./generator-service/Dockerfile
    container_name: con-gendata
    depends_on:
      - receiver-service
    networks:
      - gendata-network
    restart: unless-stopped

networks:
  gendata-network:
    driver: bridge

