#version: '3.8'

services:
  receiver-service:
    build:
      context: .
      dockerfile: ./receiver-service/Dockerfile
    container_name: con-receiver
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - gendata-network
    restart: unless-stopped
    # Ограничение логов Docker
    logging:
      driver: "json-file"
      options:
        max-size: "10m"      # Максимальный размер одного лог-файла
        max-file: "3"        # Количество ротируемых файлов
        compress: "true"     # Сжатие старых логов

  generator-service:
    build:
      context: .
      dockerfile: ./generator-service/Dockerfile
    container_name: con-gendata
    depends_on:
      - receiver-service
    networks:
      - gendata-network
    restart: unless-stopped
    # Ограничение логов Docker
    logging:
      driver: "json-file"
      options:
        max-size: "5m"       # Максимальный размер одного лог-файла
        max-file: "2"        # Количество ротируемых файлов
        compress: "true"     # Сжатие старых логов
        
networks:
  gendata-network:
    driver: bridge

